trigger:
  branches:
    include:
      - feature/*

stages:

# -------------------------
# 1. BUILD STAGE
# -------------------------
- stage: Build
  jobs:
    - job: BuildJob
      pool:
        name: 'MyLocalMachine'

      steps:
        - checkout: self

        - script: |
            "C:\Users\param\AppData\Local\Programs\Python\Python313\python.exe" --version
          displayName: 'Verify Python Version'

        - powershell: |
            $pyFiles = git ls-files '*.py'
            foreach ($file in $pyFiles) {
                & "C:\Users\param\AppData\Local\Programs\Python\Python313\python.exe" -m py_compile $file
            }
          displayName: 'Validate Python syntax'


# -------------------------
# 2. VALIDATION STAGE (DAB)
# -------------------------
- stage: Validate_DAB
  dependsOn: Build
  jobs:
    - job: ValidateJob
      pool:
        name: 'MyLocalMachine'

      steps:
        - checkout: self

        - task: PowerShell@2
          displayName: 'Validate Databricks Asset Bundle (Dry Run)'
          inputs:
            targetType: 'inline'
            script: |
                Write-Host "Checking Databricks CLI..."
                & "C:\Users\param\AppData\Local\Microsoft\WinGet\Packages\Databricks.DatabricksCLI_Microsoft.Winget.Source_8wekyb3d8bbwe\databricks.exe" --version

                $env:DATABRICKS_HOST=$(DBHOST)
                $env:DATABRICKS_TOKEN=$(PAT)

                Write-Host "Validating DEV target..."
                & "C:\Users\param\AppData\Local\Microsoft\WinGet\Packages\Databricks.DatabricksCLI_Microsoft.Winget.Source_8wekyb3d8bbwe\databricks.exe" bundle validate -t dev  

                Write-Host "Validating STAGE target..."
                & "C:\Users\param\AppData\Local\Microsoft\WinGet\Packages\Databricks.DatabricksCLI_Microsoft.Winget.Source_8wekyb3d8bbwe\databricks.exe" bundle validate -t stage  

                Write-Host "Validating PROD target..."
                & "C:\Users\param\AppData\Local\Microsoft\WinGet\Packages\Databricks.DatabricksCLI_Microsoft.Winget.Source_8wekyb3d8bbwe\databricks.exe" bundle validate -t prod  

# -------------------------
# 3. SIMULATED DEPLOYMENT
# -------------------------
- stage: Simulated_Deploy
  dependsOn: Validate_DAB
  condition: succeeded()
  jobs:
    - job: DeployJob
      pool:
        name: 'MyLocalMachine'

      steps:
        - script: |
            echo "Simulating deployment pipeline..."
            echo "Feature branch → Dev validation"
            echo "Develop branch → Stage validation"
            echo "Main branch → Prod validation"
            echo "Pipeline executed successfully!"
          displayName: 'Simulated Deployment Flow'